# gitlab-ci

stages:
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y git wget zip unzip
  - curl -s toast.sh/install-v3 | bash

build:
  stage: build
  image: php:5.6
  script:
    - ~/toaster/toast.sh build php
  artifacts:
    paths:
      - target/

deploy:
  stage: deploy
  image: python:latest
  script:
    - pip install awscli
    - ~/toaster/toast.sh releases bucket public

after_script:
  - ls -al target
