# gitlab-ci

stages:
  - build
  - release

before_script:
  - curl -s toast.sh/install-v3 | bash

build:
  stage: build
  image: maven:latest
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/

release:
  stage: release
  image: python:latest
  script:
    - pip install awscli
    - ~/toaster/toast.sh release bucket public

after_script:
  - ls -alh target
