# gitlab-ci

stages:
  - build
  - releases

before_script:
  - curl -s toast.sh/install-v3 | bash

build:
  stage: build
  image: php:7.0
  script:
    - ~/toaster/toast.sh prepare
    - ~/toaster/toast.sh build webapp
  artifacts:
    paths:
      - target/

releases:
  stage: releases
  image: python:latest
  script:
    - pip install awscli
    - ~/toaster/toast.sh releases bucket public

after_script:
  - ls -alh target
